### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by Dialga** [mlatu-lang/mlatu#35]
The local copy of the license in the README is 404'd.
https://github.com/mlatu-lang/mlatu/blob/main/LICENSE.md

**Comment by brightly-salty** [comment]
Hi, this is fixed on the ‘rust’ branch. I’m planning to merge it soon

**Comment by brightly-salty** [comment]
It occurs because the Readme and Livense are located in the docs folder, which GitHub then pulls from to disparu the README, and somehow the link resolution messed up
